<%@ Page Title="" Language="C#" MasterPageFile="~/Default.Master" AutoEventWireup="true" CodeBehind="Faq.aspx.cs" Inherits="HimsIndia.Faq" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="main-banner-w3l-2">
		<header>
			
		</header>

		</div>

	<div class="breadcrumb-agile">
		<nav aria-label="breadcrumb">
			<ol class="breadcrumb">
				<li class="breadcrumb-item">
					<a href="/Home">Home</a>
				</li>
				<li class="breadcrumb-item active" aria-current="page">FAQs</li>
			</ol>
		</nav>
	</div>
	<p></p>
    <div class="container py-xl-5 py-lg-3">

<div class="WordSection1">
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:7.7pt;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'><strong><span style='font-size:21px;line-height:107%;font-family:"Cambria",serif;color:#17365D;'>FAQs &ndash; Frequently Asked Questions &ndash; for Models and Clients&nbsp;</span></strong></p>
    <p style='margin-top:0cm;margin-right:-1.7pt;margin-bottom:17.95pt;margin-left:-1.45pt;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'><br></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.7pt;margin-left:-.25pt;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'><strong><span style="font-size:20px;line-height:103%;">I cannot log in or forgot my username and password?&nbsp;</span></strong></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.25pt;margin-left:-.25pt;text-indent:-.5pt;line-height:104%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>You have the option to reset your password at the user login. Only registered models or clients can log in.</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:1.45pt;margin-left:0cm;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.7pt;margin-left:-.25pt;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'><strong><span style="font-size:20px;line-height:103%;">What is my portfolio?&nbsp;</span></strong></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.25pt;margin-left:-.25pt;text-indent:-.5pt;line-height:104%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>With your online portfolio, you can upload documents, existing Comp cards or simply a picture folder with your most beautiful photos. Then clients can download them.</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:1.45pt;margin-left:0cm;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.7pt;margin-left:-.25pt;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'><strong><span style="font-size:20px;line-height:103%;">How do I edit my profile?&nbsp;</span></strong></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.25pt;margin-left:-.25pt;text-indent:-.5pt;line-height:104%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>If you are logged in, you will find all functions on the left side of your overview page! Under &apos;My Account&apos; and &apos;My Online Profile&apos; you can complete and edit all data.</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:1.45pt;margin-left:0cm;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.7pt;margin-left:-.25pt;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'><strong><span style="font-size:20px;line-height:103%;">Do I have to enter all my data in my online profile?&nbsp;</span></strong></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.25pt;margin-left:-.25pt;text-indent:-.5pt;line-height:104%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>The more complete your profile, the higher the chance of being discovered and booked by clients.</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:1.45pt;margin-left:0cm;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.7pt;margin-left:-.25pt;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'><strong><span style="font-size:20px;line-height:103%;">Which photos should I upload?&nbsp;</span></strong></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.25pt;margin-left:-.25pt;text-indent:-.5pt;line-height:104%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>The photos you upload should show how versatile and adaptable you are. We suggest you showcase yourself in a variety of ways ie outfits, styles and situations. Demonstrating selfconfidence and a positive attitude.</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:1.7pt;margin-left:0cm;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.7pt;margin-left:-.25pt;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'><strong><span style="font-size:20px;line-height:103%;">How can I apply for Hims India Model?&nbsp;</span></strong></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.25pt;margin-left:-.25pt;text-indent:-.5pt;line-height:104%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>In each model category you will find links to the application form. There you can apply.</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:1.45pt;margin-left:0cm;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.7pt;margin-left:-.25pt;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'><strong><span style="font-size:20px;line-height:103%;">What criteria do you use to choose models?&nbsp;</span></strong></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.25pt;margin-left:-.25pt;text-indent:-.5pt;line-height:104%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>Since self-confidence and personality are a prerequisite for a model, we pay attention to how you look in your application photos. Based on the application photos, we can decide if somebody has the potential to be a model.</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:1.45pt;margin-left:0cm;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.7pt;margin-left:-.25pt;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'><strong><span style="font-size:20px;line-height:103%;">How can I contact you?&nbsp;</span></strong></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:1.95pt;margin-left:-.25pt;text-indent:-.5pt;line-height:104%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>Under &apos;Contact&apos; you will find all our contact information to get in touch with us!</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.25pt;margin-left:.5pt;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;margin:0cm;'><span style="font-size:20px;line-height:107%;">&nbsp;</span></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:3.65pt;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:center;'><strong><span style="font-size:20px;line-height:107%;">&nbsp;</span></strong></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:3.65pt;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:center;'><strong><span style="font-size:20px;line-height:107%;">&nbsp;</span></strong></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:3.65pt;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:center;'><strong><span style="font-size:20px;line-height:107%;">&nbsp;</span></strong></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:3.65pt;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:center;'><strong><span style="font-size:20px;line-height:107%;">&nbsp;</span></strong></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:3.65pt;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:center;'><strong><span style="font-size:20px;line-height:107%;">&nbsp;</span></strong></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:3.65pt;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:center;'><strong><span style="font-size:20px;line-height:107%;">&nbsp;</span></strong></p>
    <h1 style='margin-top:0cm;margin-right:.25pt;margin-bottom:0cm;margin-left:.5pt;text-align:center;text-indent:-.5pt;line-height:107%;font-size:20px;font-family:"Calibri",sans-serif;color:black;'>FOR MODELS: GENERAL &amp; FIND MODELS</h1>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:3.65pt;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:center;'><strong><span style="font-size:20px;line-height:107%;">&nbsp;</span></strong></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.7pt;margin-left:-.25pt;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'><strong><span style="font-size:20px;line-height:103%;">Do I have to accept all orders?&nbsp;</span></strong></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.25pt;margin-left:-.25pt;text-indent:-.5pt;line-height:104%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>Absolutely not, you are completely independent. That is to say, you decide for yourself which orders you wish to accept and which not!</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:1.45pt;margin-left:0cm;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.7pt;margin-left:-.25pt;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'><strong><span style="font-size:20px;line-height:103%;">Will I get a model job as a model?&nbsp;</span></strong></p>
    <p style='margin-top:0cm;margin-right:12.4pt;margin-bottom:.25pt;margin-left:-.25pt;text-indent:-.5pt;line-height:104%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>This depends on many factors such as season, popular model type, and so on. In addition, it is also important that you always upload current and beautiful photos in your model profile. Unfortunately, we can not promise at 100% that you will get a model job.</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:1.45pt;margin-left:0cm;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.7pt;margin-left:-.25pt;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'><strong><span style="font-size:20px;line-height:103%;">How can I get jobs as a model?&nbsp;</span></strong></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.25pt;margin-left:-.25pt;text-indent:-.5pt;line-height:104%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>If you are logged in as a model, you will find a section &apos;Job List&apos; at the top of the menu. You can always browse and actively apply for available jobs.</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:1.45pt;margin-left:0cm;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.7pt;margin-left:-.25pt;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'><strong><span style="font-size:20px;line-height:103%;">Do I have to pay Hims India -models if I am booked?&nbsp;</span></strong></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.25pt;margin-left:-.25pt;text-indent:-.5pt;line-height:104%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>No, we are not a modeling agency so you do not pay us any commission if booked.</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:1.5pt;margin-left:0cm;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.7pt;margin-left:-.25pt;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'><strong><span style="font-size:20px;line-height:103%;">How can I apply for jobs?&nbsp;</span></strong></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.25pt;margin-left:-.25pt;text-indent:-.5pt;line-height:104%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>As soon as you find a suitable job in your job list, you can simply click on &apos;Apply for this job&apos; in the detail view.</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:1.45pt;margin-left:0cm;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.7pt;margin-left:-.25pt;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'><strong><span style="font-size:20px;line-height:103%;">How can I get in contact with agents, photographers and/or film production companies?&nbsp;</span></strong></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.25pt;margin-left:-.25pt;text-indent:-.5pt;line-height:104%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>Naturally, through your personal profile, you can easily get in touch with potential agents etc. In addition, you can also be contacted.</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:1.45pt;margin-left:0cm;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.7pt;margin-left:-.25pt;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'><strong><span style="font-size:20px;line-height:103%;">Where will I get model jobs?&nbsp;</span></strong></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.25pt;margin-left:-.25pt;text-indent:-.5pt;line-height:104%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>You can decide where you accept jobs, either in your area or internationally.</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:1.45pt;margin-left:0cm;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.7pt;margin-left:-.25pt;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'><strong><span style="font-size:20px;line-height:103%;">How much can I earn on a model assignment?&nbsp;</span></strong></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.25pt;margin-left:-.25pt;text-indent:-.5pt;line-height:104%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>The fees are of course different and depend on the client and the order. By all means, please check with the client directly!</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:1.5pt;margin-left:0cm;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.7pt;margin-left:-.25pt;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'><strong><span style="font-size:20px;line-height:103%;">Is my data public?&nbsp;</span></strong></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.25pt;margin-left:-.25pt;text-indent:-.5pt;line-height:104%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>No, it is used exclusively on our Hims India portal and only verified agents, photographers and film companies have access to your information.</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:1.45pt;margin-left:0cm;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.25pt;margin-left:.5pt;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;margin:0cm;'><span style="font-size:20px;line-height:107%;">&nbsp;</span></p>
    <h1 style='margin-top:0cm;margin-right:.15pt;margin-bottom:0cm;margin-left:.5pt;text-align:center;text-indent:-.5pt;line-height:107%;font-size:20px;font-family:"Calibri",sans-serif;color:black;'>FOR CLIENTS: FIND GENERAL &amp; MODELS</h1>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:3.65pt;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;text-align:center;'><strong><span style="font-size:20px;line-height:107%;">&nbsp;</span></strong></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.7pt;margin-left:-.25pt;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'><strong><span style="font-size:20px;line-height:103%;">I can not log in, or have forgotten my username and password.&nbsp;</span></strong></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.25pt;margin-left:-.25pt;text-indent:-.5pt;line-height:104%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>In case you can not log in, please reset your password. Either directly in the log-in area you can do that or in your profile.</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:1.45pt;margin-left:0cm;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.7pt;margin-left:-.25pt;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'><strong><span style="font-size:20px;line-height:103%;">How can I find models?&nbsp;</span></strong></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.25pt;margin-left:-.25pt;text-indent:-.5pt;line-height:104%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>When you are logged in, you will find the option &apos;Model Search&apos; in your menu. Thus you can identify exactly the right models for your orders through a variety of filters.</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:1.45pt;margin-left:0cm;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.7pt;margin-left:-.25pt;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'><strong><span style="font-size:20px;line-height:103%;">Can I edit my jobs at any time?&nbsp;</span></strong></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.25pt;margin-left:-.25pt;text-indent:-.5pt;line-height:104%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>Of course, you can update and edit jobs at any time.</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:1.5pt;margin-left:0cm;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.7pt;margin-left:-.25pt;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'><strong><span style="font-size:20px;line-height:103%;">How can I publish jobs?&nbsp;</span></strong></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.25pt;margin-left:-.25pt;text-indent:-.5pt;line-height:104%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>In your client profile, you can always post a &quot;job&quot;. There you can enter all important information regarding the job. When you click on &quot;Post Job&quot; below, your job will be public. After that, Models can apply.</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:1.45pt;margin-left:0cm;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.7pt;margin-left:-.25pt;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'><strong><span style="font-size:20px;line-height:103%;">Can I find jobs myself?&nbsp;</span></strong></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.25pt;margin-left:-.25pt;text-indent:-.5pt;line-height:104%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>Of course, you can! As a client, you have access to our &apos;job list&apos;. Thus you can search for jobs there and apply at the click of a mouse.</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:1.45pt;margin-left:0cm;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.7pt;margin-left:-.25pt;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'><strong><span style="font-size:20px;line-height:103%;">Which models can I book?&nbsp;</span></strong></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.25pt;margin-left:-.25pt;text-indent:-.5pt;line-height:104%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>We have models from all different categories &ndash; from baby models, child models, 50 plus models through to fitness or plus size models.</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:1.45pt;margin-left:0cm;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.7pt;margin-left:-.25pt;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'><strong><span style="font-size:20px;line-height:103%;">How much commission is to be paid to you?&nbsp;</span></strong></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.25pt;margin-left:-.25pt;text-indent:-.5pt;line-height:104%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>Since we are not a modeling agency &ndash; rather a modern online model portal &ndash; you don&apos;t have to pay any commission!</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:1.5pt;margin-left:0cm;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>&nbsp;</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.7pt;margin-left:-.25pt;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'><strong><span style="font-size:20px;line-height:103%;">How can I delete my profile?&nbsp;</span></strong></p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.25pt;margin-left:-.25pt;text-indent:-.5pt;line-height:104%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>If you would like to delete your profile, please send us an email and we will deactivate your account.</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.25pt;margin-left:.5pt;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;margin:0cm;'>&nbsp;</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.25pt;margin-left:-.25pt;text-indent:-.5pt;line-height:104%;font-size:16px;font-family:"Calibri",sans-serif;color:black;'>We hope you found these Frequently Asked Questions (FAQs) helpful. If you have any further questions &nbsp;</p>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.25pt;margin-left:.5pt;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:black;margin:0cm;'>please contact us. <u><span style="color:blue;">biz@himsindia.com</span></u> / <u><span style="color:blue;">care@himsindia.com</span></u> &nbsp;</p>
</div>
        </div>
<p></p>
</asp:Content>
