<%@ Page Title="" Language="C#" MasterPageFile="~/Default.Master" AutoEventWireup="true" CodeBehind="UserAgreementClients.aspx.cs" Inherits="HimsIndia.UserAgreementClients" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="main-banner-w3l-2">
		<header>
			
		</header>

		</div>

	<div class="breadcrumb-agile">
		<nav aria-label="breadcrumb">
			<ol class="breadcrumb">
				<li class="breadcrumb-item">
					<a href="/Home">Home</a>
				</li>
				<li class="breadcrumb-item active" aria-current="page">User Agreement for Clients (IN) </li>
			</ol>
		</nav>
	</div>
    <div class="container py-xl-5 py-lg-3">
	<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:23.6pt;text-align:center;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'><span style='font-size:35px;line-height:107%;font-family:"Cambria",serif;color:#17365D;'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:23.6pt;text-align:center;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'><span style='font-size:35px;line-height:107%;font-family:"Cambria",serif;color:#17365D;'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:16.6pt;text-align:center;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'><span style='font-size:35px;line-height:107%;font-family:"Cambria",serif;color:#17365D;'>User Agreement for Clients (IN)&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:-1.35pt;margin-bottom:15.3pt;margin-left:16.6pt;text-align:left;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'><br></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:18.0pt;text-align:left;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'><span style='font-family:"Arial",sans-serif;'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:.35pt;margin-bottom:.6pt;margin-left:17.75pt;text-align:justify;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'>PLEASE READ THESE TERMS AND CONDITIONS CAREFULLY BEFORE USING THIS PORTAL</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:9.65pt;margin-left:18.0pt;text-align:left;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'>&nbsp;</p>
<h1 style='margin-top:0cm;margin-right:0cm;margin-bottom:4.7pt;margin-left:17.75pt;text-indent:-.5pt;line-height:107%;font-size:19px;font-family:"Calibri",sans-serif;color:#171717;'>Introduction</h1>
<p style='margin-top:0cm;margin-right:.35pt;margin-bottom:25.6pt;margin-left:17.75pt;text-align:justify;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'>We are a platform for models, photographers, agencies, make-up artists and other professionals in the modeling business. We allow models and potential clients to get in touch and do business.</p>
<h1 style='margin-top:0cm;margin-right:0cm;margin-bottom:4.7pt;margin-left:17.75pt;text-indent:-.5pt;line-height:107%;font-size:19px;font-family:"Calibri",sans-serif;color:#171717;'>Definitions</h1>
<p style='margin-top:0cm;margin-right:.35pt;margin-bottom:.6pt;margin-left:17.75pt;text-align:justify;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'>&ldquo;Website&rdquo;: www.himsindia.com</p>
<p style='margin-top:0cm;margin-right:.35pt;margin-bottom:0cm;margin-left:17.75pt;text-align:justify;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'>&ldquo;Portal/Platform&rdquo;: the area of the Website accessible only with valid credentials and through which registered Professionals/Clients are able to book a Model for a certain job (see Scope of Services); &ldquo;Model&rdquo;: models visiting the Website or using the Platform.</p>
<p style='margin-top:0cm;margin-right:.35pt;margin-bottom:0cm;margin-left:17.75pt;text-align:justify;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'>&ldquo;Professionals/Clients&rdquo;: agents/agencies, photographers, makeup artists, stylists and other professionals using the Platform; Hereinafter also referred to as &ldquo;you&rdquo;; &ldquo;User&rdquo;: Model or Professional/Client.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.5pt;margin-left:18.0pt;text-align:left;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'>&nbsp;</p>
<h1 style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:17.75pt;text-indent:-.5pt;line-height:107%;font-size:19px;font-family:"Calibri",sans-serif;color:#171717;'>These Terms</h1>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:18.0pt;text-align:left;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'><strong><span style="font-size:19px;line-height:107%;">&nbsp;</span></strong></p>
<p style='margin-top:0cm;margin-right:.35pt;margin-bottom:16.45pt;margin-left:17.75pt;text-align:justify;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'>These terms and conditions cover the terms on which we make our Platform (including digital content) available to you. Please read these terms carefully before you submit your order to us. These terms tell you who we are, how we will provide the services on the Platform and digital content to you, how you and we may change or end the contract, what to do if there is a problem and other important changes. If you think there is a change in these terms, please contact us to discuss this.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:17.75pt;text-align:left;text-indent:-.5pt;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'><strong><span style="font-size:19px;line-height:107%;">How to Contact Us&nbsp;</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:18.0pt;text-align:left;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'><strong><span style="font-size:19px;line-height:107%;">&nbsp;</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:6.85pt;margin-left:0cm;text-align:left;text-indent:0cm;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'><span style='font-size:13px;line-height:103%;font-family:"Segoe UI Symbol",sans-serif;'></span><span style='font-size:13px;line-height:103%;font-family:"Arial",sans-serif;'>&nbsp;&nbsp; &nbsp;</span>You can contact us by telephoning our Support by writing to us at - &nbsp;care@himsindia.com</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.5pt;margin-left:18.0pt;text-align:left;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'>&nbsp;</p>
<h1 style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:17.75pt;text-indent:-.5pt;line-height:107%;font-size:19px;font-family:"Calibri",sans-serif;color:#171717;'>Contract with You</h1>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:18.0pt;text-align:left;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'><strong><span style="font-size:19px;line-height:107%;">&nbsp;</span></strong></p>
<p style='margin-top:0cm;margin-right:.35pt;margin-bottom:0cm;margin-left:17.75pt;text-align:justify;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'>You agree that by clicking on the button &quot;Apply now&quot; or &quot;Apply for free&quot; you will complete your application with Hims India and at this point, a contract will come into existence between you and us. This agreement includes this user agreement and the <u>privacy notice</u></p>
<p style='margin-top:0cm;margin-right:.35pt;margin-bottom:2.05pt;margin-left:17.75pt;text-align:justify;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'>If our contract partner is a legal entity or a partnership, you declare with the registration that you may act on their behalf. Should this transpire to be incorrect, we reserve our rights to immediately terminate this agreement.</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:18.0pt;text-align:left;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'>&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.5pt;margin-left:18.0pt;text-align:left;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'>&nbsp;</p>
<h1 style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:17.75pt;text-indent:-.5pt;line-height:107%;font-size:19px;font-family:"Calibri",sans-serif;color:#171717;'>Access to Services and Benefits</h1>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:18.0pt;text-align:left;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'><strong><span style="font-size:19px;line-height:107%;">&nbsp;</span></strong></p>
<ul style="list-style-type: undefined;margin-left:25.25px;">
    <li>Your profile will be activated immediately after your subscription contract has been concluded and you will receive access to your profile (login and password).</li>
    <li>You may only have ONE Hims India account on the Platform and you warrant to us that you have created it with your real name and that your data is authentic.</li>
    <li>We may suspend your profile or delete your profile from the Platform if you are in breach of your agreement with us or in breach of any acceptable website use policy published on the Platform from time to time.</li>
    <li>We do not guarantee that the Platform, or any content on it, will always be available or be uninterrupted (we may, for example, need to suspend access to the Platform to carry out necessary maintenance). We will try and give you reasonable notice of any suspension.</li>
    <li>You must keep your account details safe.</li>
    <li>If you are provided with a user identification code, password or any other piece of information as part of our security procedures, you must treat such information as confidential. You must not disclose it to any third party.</li>
    <li>We have the right to disable any user identification code or password, whether chosen by or allocated by us, at any time, if in our reasonable opinion you have failed to comply with any terms of use.</li>
    <li>You may not make publicly available or otherwise disclose to third parties content from the Platform which contains content uploaded by other Users or otherwise includes personal data of other Users (i.e. no screenshots, printouts, photos, etc. of lists, conversations, profiles, details, etc.) [MW1] or perform any action which may negatively affect the operability of the Platform or our infrastructure.</li>
    <li>If you know or suspect that anyone other than you knows your user identification code or password, you must promptly change your password and notify us at <u><span style="color:blue;">care@himsindia.com</span></u> &nbsp;</li>
</ul>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:18.0pt;text-align:left;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'>&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.75pt;margin-left:18.0pt;text-align:left;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'>&nbsp;</p>
<h1 style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:17.75pt;text-indent:-.5pt;line-height:107%;font-size:19px;font-family:"Calibri",sans-serif;color:#171717;'>Notifications and Personal Data</h1>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:18.0pt;text-align:left;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'><strong><span style="font-size:19px;line-height:107%;">&nbsp;</span></strong></p>
<ul style="list-style-type: undefined;margin-left:25.25px;">
    <li>We will only use your personal data as set out in our<a href="https://go-models.com/privacy-notice"><span style="color:#171717;">&nbsp;</span></a><a href="https://go-models.com/privacy-notice"><span style="color:#171717;">privacy notice</span></a><a href="https://go-models.com/privacy-notice"><span style="color:#171717;">&nbsp;</span></a>and as provided by you in your profile.</li>
    <li>You authorize us to contact and notify you through the following communication channels: email, Skype, telephone (including SMS/WhatsApp) and postal services as well as through social media channels (e.g. Facebook, Instagram, etc). We will use the information you provide. You undertake to keep your data updated and to inform us promptly of any changes. Should you wish to no longer receive such information please notify us of this at <u><span style="color:blue;">care@himsindia.com</span></u> &nbsp;</li>
    <li>When we use the words &ldquo;writing&rdquo; or &ldquo;written&rdquo; in these terms, this includes emails and digital messages.</li>
</ul>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.5pt;margin-left:18.0pt;text-align:left;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'>&nbsp;</p>
<h1 style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:17.75pt;text-indent:-.5pt;line-height:107%;font-size:19px;font-family:"Calibri",sans-serif;color:#171717;'>Information you provide &amp; Content you upload to the Platform</h1>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:18.0pt;text-align:left;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'><strong><span style="font-size:19px;line-height:107%;">&nbsp;</span></strong></p>
<p style='margin-top:0cm;margin-right:.35pt;margin-bottom:2.05pt;margin-left:17.75pt;text-align:justify;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'>During your registration and subscription, you may upload content to the Platform (such as text, images, audio, videos, etc.) and share information with us. You represent and warrant that the information you provide in your profile is accurate and that your content does not violate any law or morality or any third party&rsquo;s intellectual property rights and that any necessary consents required under data protection laws have been obtained and remain in force.</p>
<p style='margin-top:0cm;margin-right:.35pt;margin-bottom:15.0pt;margin-left:17.75pt;text-align:justify;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'>Whenever you upload content to the Platform, you grant us the right to use such content in the course of providing our subscription services to you. You will at all times remain the legal owner of uploaded content, however, by uploading the content to the Platform, you grant Hims India a non-exclusive, transferable, sublicensable, royalty-free, and worldwide license to host, use, modify, copy or display and create derivative works of your content on the Platform. Please note that the Portal is not accessible to the general public but your content will be visible to approved Professionals/Clients of the Portal (e.g. partners, photographers, advertising agencies or make-up artists). Our license to use your content will terminate when you either individually delete your content from the Platform or your subscription has expired or been otherwise terminated in accordance with the terms of the agreement.</p>
<p style='margin-top:0cm;margin-right:.35pt;margin-bottom:14.8pt;margin-left:17.75pt;text-align:justify;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'>As you are the owner of your own content and we only have a non-exclusive right to use it in accordance with the terms of the agreement, you may make your content available to others at your will.</p>
<p style='margin-top:0cm;margin-right:.35pt;margin-bottom:16.7pt;margin-left:17.75pt;text-align:justify;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'>Please note that your surname, telephone number and email address will not be made available to other Users on the Platform.</p>
<h1 style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:17.75pt;text-indent:-.5pt;line-height:107%;font-size:19px;font-family:"Calibri",sans-serif;color:#171717;'>Information we Contribute to the Platform</h1>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:18.0pt;text-align:left;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'><strong><span style="font-size:19px;line-height:107%;">&nbsp;</span></strong></p>
<ul style="list-style-type: undefined;margin-left:25.25px;">
    <li>By using Hims India, you may be confronted with content from other Users. Since we do not verify the content of our Users, we assume no liability for any damages or liability arising as a result of third party content.</li>
    <li>Hims India reserves the right to restrict your access if we believe that you have violated one or more of the terms of this agreement.</li>
    <li>We are the owner or the licensee of all intellectual property rights that we have contributed to the Platform. Those works are protected by copyright laws and treaties around the world. All such rights are reserved.</li>
    <li>Our status (and that of any identified contributors) as the authors of content we have contributed (excluding the data you have published) on the Platform must always be acknowledged.</li>
    <li>Although we make reasonable efforts to update the information on the Platform, we make no representations, warranties or guarantees, whether express or implied, that the content on our Platform is accurate, complete, up to date, or serves any particular purpose.</li>
    <li>We are not responsible for any websites we link to.</li>
    <li>Where the Platform contains links to other websites and resources provided by third parties, these links are provided for your information only. Such links should not be interpreted as approval by us of those linked websites or information you may obtain from them. We have no control over the contents of those websites or resources.</li>
    <li>User-generated content is not approved by us.</li>
    <li>We would like to ask that you report other Users&rsquo; behavior which violates these terms and/or any applicable laws by contacting us at care@himsindia.com</li>
</ul>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.5pt;margin-left:18.0pt;text-align:left;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'>&nbsp;</p>
<h1 style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:17.75pt;text-indent:-.5pt;line-height:107%;font-size:19px;font-family:"Calibri",sans-serif;color:#171717;'>Scope of Services</h1>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:18.0pt;text-align:left;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'><strong><span style="font-size:19px;line-height:107%;">&nbsp;</span></strong></p>
<p style='margin-top:0cm;margin-right:.35pt;margin-bottom:17.15pt;margin-left:17.75pt;text-align:justify;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'>Through the Platform, Models and Professionals/Clients will be able to connect in a login-protected area. Hims India provides the following functions and scope:</p>
<ul style="list-style-type: undefined;margin-left:25.25px;">
    <li>Your profile will be visible to other Users</li>
    <li>You can create and get job inquiries in your area or internationally.</li>
    <li>Model search and Model-details</li>
    <li>Favourite: You can mark Models directly as favourites.</li>
    <li>TFP-Jobs: you can create jobs on a TFP (Time-For-Prints) basis.</li>
    <li>You can upload up to 30 photos to your profile/photos are automatically optimized for screen display.</li>
</ul>
<p style='margin-top:0cm;margin-right:.15pt;margin-bottom:0cm;margin-left:18.0pt;text-align:justify;text-indent:0cm;line-height:normal;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'><em>Please note that any modeling jobs offered by Professionals/Clients are strictly arrangements between the Model and the Professionals/Clients. Any jobs or other arrangements for work will be strictly arrangements between Models and the Professionals/Clients.</em></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:2.4pt;margin-left:18.0pt;text-align:left;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'>&nbsp;</p>
<h1 style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:17.75pt;text-indent:-.5pt;line-height:107%;font-size:19px;font-family:"Calibri",sans-serif;color:#171717;'><span style="font-size:21px;line-height:107%;">Additional Services&nbsp;</span></h1>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:18.0pt;text-align:left;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'><strong>&nbsp;</strong></p>
<p style='margin-top:0cm;margin-right:.35pt;margin-bottom:18.35pt;margin-left:17.75pt;text-align:justify;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'>Your subscription is provided free of charge. However, from time to time you may order additional services requiring payment in which case please note that additional terms may apply to these services and you will be asked to agree to those before submitting the order.</p>
<h1 style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:17.75pt;text-indent:-.5pt;line-height:107%;font-size:19px;font-family:"Calibri",sans-serif;color:#171717;'><span style="font-size:21px;line-height:107%;">Changes to the Platform&nbsp;</span></h1>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:18.0pt;text-align:left;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'><strong><span style="font-size:21px;line-height:107%;">&nbsp;</span></strong></p>
<p style='margin-top:0cm;margin-right:.35pt;margin-bottom:18.6pt;margin-left:17.75pt;text-align:justify;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'>We may make changes to the Platform or the services we provide from time to time to reflect changes to our users&apos; needs or to reflect changes in relevant laws and regulatory requirements or to implement minor technical adjustments and improvements, for example, to address a security threat. If we intend to make more significant changes to the services or the Portal, we will try to give you reasonable notice of any major changes.</p>
<h1 style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:17.75pt;text-indent:-.5pt;line-height:107%;font-size:19px;font-family:"Calibri",sans-serif;color:#171717;'><span style="font-size:21px;line-height:107%;">Liability&nbsp;</span></h1>
<ul style="list-style-type: undefined;margin-left:25.25px;">
    <li>Hims India is under no circumstances liable for the content, correctness and completeness, etc. of data transmitted or retrieved and for data that is accessible via Hims India. In particular, Hims India is not obliged to verify the contents for possible violations of the applicable law. This also applies to content and/or documents exchanged between Users on the Platform.</li>
    <li>Should content uploaded by you to the Platform infringe any rights of any third party, we may delete such content without notice, unless you provide reasonable evidence of your having obtained the right to use said content.</li>
    <li>You shall indemnify and hold harmless Hims India from and against any and all claims of third-parties against Hims India arising from an infringement of their rights by any content uploaded by you to the Platform or otherwise provided to us. You assume all reasonable costs incurred by Hims India due to an infringement of such third-party rights, including all reasonable legal-defence costs. Hims India is neither responsible for the jobs arranged between Users on the Platform, nor will Hims India be held responsible for any job-related issues arising between the Users, including breaches of agreements entered into between the Users. You agree and acknowledge that Hims India is not party to any jobs or other arrangements entered into between Users and Hims India is not therefore responsible for any failure of a User to comply with the agreed terms of such job or arrangements and neither is Hims India responsible for expenses (e.g. travelling expenses) incurred by a User in connection with such job or arrangement.</li>
    <li>We do not exclude or limit in any way our liability to you where it would be unlawful to do so. This includes liability for death or personal injury caused by our negligence or the negligence of our employees, agents or subcontractors and for fraud or fraudulent misrepresentation.</li>
    <li>We have no liability to you for any loss of profit, loss of business, business interruption, or loss of business opportunity.</li>
    <li>If any employee of Hims India comments on a Model&rsquo;s suitability for a certain job or content uploaded to the Platform by you in any means of communication, these comments will be considered personal opinions, for which Hims India will not be held responsible.</li>
</ul>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.5pt;margin-left:18.0pt;text-align:left;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'>&nbsp;</p>
<h2 style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:17.75pt;text-indent:-.5pt;line-height:107%;font-size:19px;font-family:"Calibri",sans-serif;color:#171717;'>How To End The Contract With Us</h2>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:18.0pt;text-align:left;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'><strong>&nbsp;</strong></p>
<p style='margin-top:0cm;margin-right:.35pt;margin-bottom:15.0pt;margin-left:17.75pt;text-align:justify;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'>You may end the contract with us at any time by emailing us at care@himsindia.com. Please provide your hims-code, company name, surname and email address.</p>
<p style='margin-top:0cm;margin-right:.35pt;margin-bottom:16.45pt;margin-left:17.75pt;text-align:justify;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'>Please note it may take us circa 14 days to action your request and, once done, your access to the Platform will cease. Any content you may have uploaded to the Platform will remain subject to the license granted to us in these terms.</p>
<h2 style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:17.75pt;text-indent:-.5pt;line-height:107%;font-size:19px;font-family:"Calibri",sans-serif;color:#171717;'>Our Right To Cancel Your Contract</h2>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:18.0pt;text-align:left;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'><strong><span style="font-size:19px;line-height:107%;">&nbsp;</span></strong></p>
<p style='margin-top:0cm;margin-right:.35pt;margin-bottom:9.2pt;margin-left:17.75pt;text-align:justify;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'>We may end the contract at any time by writing to you if:</p>
<ul style="list-style-type: undefined;margin-left:25.25px;">
    <li>you do not, within a reasonable time of us asking for it, provide us with information that is necessary for us to provide the services;</li>
    <li>you use the Platform in any way that breaches any applicable local, national or international law or regulation, in any way that is unlawful or fraudulent, or has any unlawful or fraudulent purpose or effect, for the purpose of harming or attempting to harm any person, to bully, insult, intimidate or humiliate any person, or to transmit, or procure the sending of, any unsolicited or unauthorized advertising or promotional material or any other form of similar solicitation (spam); We can take legal action against your such activities.</li>
    <li>You have otherwise committed a breach of these terms or any acceptable website use policy published on the Platform from time to time.</li>
</ul>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.5pt;margin-left:18.0pt;text-align:left;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'>&nbsp;</p>
<h2 style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:17.75pt;text-indent:-.5pt;line-height:107%;font-size:19px;font-family:"Calibri",sans-serif;color:#171717;'>General Provisions</h2>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:1.15pt;margin-left:18.0pt;text-align:left;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'>&nbsp;</p>
<ul style="list-style-type: undefined;margin-left:25.25px;">
    <li>You may not assign, transfer, mortgage, charge, sub-contract, declare a trust over or deal in any manner with all or any of its rights or obligations under this agreement without Hims India prior written consent.</li>
    <li>Hims India may at any time assign, transfer, mortgage, charge, subcontract, or deal in any other manner with all or any of its rights of obligations under this agreement. We will always tell you in writing if this happens.</li>
    <li>Hims India reserves the right to amend the terms of this agreement, without giving reasons, unless an amendment is unreasonable to you. Hims India shall give due notice of any amendments of these terms to you. If you do not object to the applicability of the revised terms within (6) weeks after receipt of said notice, the terms shall be deemed accepted and approved by you. Hims India shall inform you about your right to object (and your right to terminate) and of the relevance of the objection deadline in said notice.</li>
    <li>Unless otherwise stated in these terms, you may submit all notices to Hims India by sending an e-mail to care@himsindia.com.</li>
    <li>Statements and information about services or fee-based memberships on the Website or Platform or other advertising materials are intended solely as a description of quality and do not constitute a guarantee or warranty of any quality.</li>
    <li>Should provisions of this agreement be or become invalid, void or unenforceable, it shall be deemed deleted, but that shall not affect the validity, legality or enforceability of the rest of this agreement. The parties agree to replace an invalid and/or unenforceable provision with a valid and/or enforceable provision which comes as close as possible to the intent and economic purpose of the invalid and/or unenforceable provision. This also applies to regulatory gaps in the terms of this agreement.</li>
    <li>All agreements, subsequent changes, supplements, subsidiary agreements, etc. must be in writing with written confirmation by Hims India for their validity.</li>
    <li>These terms are governed by Indian law and you can bring legal proceedings in respect of the services we provide in the courts.</li>
</ul>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:18.0pt;text-align:left;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'>&nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.5pt;margin-left:18.0pt;text-align:left;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'>&nbsp;</p>
<h2 style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:17.75pt;text-indent:-.5pt;line-height:107%;font-size:19px;font-family:"Calibri",sans-serif;color:#171717;'>Details of Our International Support Team</h2>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:18.0pt;text-align:left;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'><strong><span style="font-size:19px;line-height:107%;">&nbsp;</span></strong></p>
<p style='margin-top:0cm;margin-right:.35pt;margin-bottom:14.8pt;margin-left:17.75pt;text-align:justify;text-indent:-.5pt;line-height:103%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'>If at any time you have any queries about these terms or about our services, please contact our Support Team below: <u><span style="color:blue;">care@himsindia.com</span></u> &nbsp;</p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:18.0pt;text-align:left;text-indent:0cm;line-height:107%;font-size:16px;font-family:"Calibri",sans-serif;color:#171717;'><span style="color:black;">&nbsp;</span></p>
        </div>
</asp:Content>
